name: CI

on:
  push:
    branches:
      - '*'
    tags:
      - '*'
  pull_request:
    branches:
      - '*'
  workflow_dispatch:

jobs:
  build:
    if: "!contains(github.event.head_commit.message, 'skip ci')"

    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        php:
          - '8.2'
        prefer:
          - 'prefer-lowest'
          - 'prefer-stable'

    name: PHP ${{ matrix.php }} --${{ matrix.prefer }}

    steps:
      - name: Checkout
        uses: checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          tools: composer:v2
          coverage: pcov

      - name: Cache dependencies
        uses: actions/cache@v1
        with:
          path: ~/.composer/cache/files
          key: composer-php-${{ matrix.php }}-${{ matrix.prefer }}-${{ hashFiles('composer.json') }}

      - name: Install dependencies
        run: |
          composer install --${{ matrix.prefer }} --no-interaction --prefer-dist --optimize-autoloader --no-suggest

      - name: Run tests
        run: |
          ./vendor/bin/phpunit --coverage-text --coverage-clover=coverage_local.xml
